language: Swift
osx_image: xcode10.2
xcode_project: FlickrFeed.xcodeproj # path to your xcodeproj folder
xcode_scheme: FlickrFeed

before_install:
  - make init

script:
  - cd Example
  - set -o pipefail
  - xcodebuild test -workspace MailyExample.xcworkspace -scheme MailyExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' | xcpretty -c 
